- id: '1583381510617'
  alias: Perform Daily Backup
  description: ''
  trigger:
  - at: 02:30:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - data_template:
      keep_days: 3
      name: 'DailyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
    service: auto_backup.snapshot_full
- id: '1583387288089'
  alias: On Start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: Islanders Theme
    service: frontend.set_theme
  - data:
      message: Home Assistant is starting up.
      title: Alert
    service: notify.mobile_app_pixel_3_xl
- id: '1584145738331'
  alias: On Shutdown
  description: ''
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant is shutting down
      title: Alert
    service: notify.mobile_app_pixel_3_xl
- id: '1584245588575'
  alias: Unlocked Door During Shower
  description: ''
  trigger:
  - entity_id: lock.front_door_locked
    for: '10'
    from: locked
    platform: state
    to: unlocked
  condition:
  - above: '.75'
    condition: numeric_state
    entity_id: sensor.upstairs_bathroom_humidity
  action:
  - data:
      message: Front door has been unlocked.
      title: Alert
    service: notify.mobile_app_pixel_3_xl
