homeassistant:
  name: Home
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

auto_backup: !include components/autobackup.yaml
automation: !include automations.yaml
breaking_changes:
camera: !include_dir_list components/cameras
cloud:
config:
frontend: !include components/frontend.yaml
google: !include components/google_calendar.yaml 
group: !include groups.yaml
hassio:
history:
http: !include components/http.yaml
logbook:
logger: !include components/logger.yaml
media_player: !include_dir_list components/media_players
mobile_app:
nest: !include components/nest.yaml
pi_hole: !include components/pi_hole.yaml
recorder: !include components/recorder.yaml
remote: !include_dir_list components/remotes
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_list components/sensors
speedtestdotnet: !include components/speedtestdotnet.yaml
system_health:
tts: !include_dir_list components/tts
uilogs:
var: !include_dir_merge_named components/vars